### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Hensel3** [lucascesarfd/underwater_snd#2]
I got the data set of.WAv here, should I convert it to.csv before I can use it

**Comment by ftanago** [comment]
@Hensel3 could you tell me how did you download the data? im unable

**Comment by lucascesarfd** [comment]
Hi @Hensel3 and @ftanago

The README was updated with the correct url. It points to the VTUAD dataset (also updated the dataset class name). The .csv can also be dowloaded with the VTUAD dataset. 

In any case, the link is here:

https://ieee-dataport.org/documents/vtuad-vessel-type-underwater-acoustic-data
