### ISSUE TITLE
Unable to access to the Database via DeeperShip Repository link

### ISSUE THREAD

**Issue by angus-xwu** [lucascesarfd/underwater_snd#4]
Hi Lucas

Thank you for your work on this project.

I was trying to get access to the database as you mentioned in the README file, but it seems the link bring me back to https://github.com/lucascesarfd/underwater_snd. 

I also found the following project may help me to download the data: https://github.com/lucascesarfd/onc_dataset but it complains as follow when I trying to download the raw .WAV files: 

![image](https://github.com/lucascesarfd/underwater_snd/assets/156045481/0c3a9579-f713-43b5-970b-08497df40f4c)

Can you help me to resolve this? or if you can give me some hint to fix it? 

Many thanks,
Angus

**Comment by psmskelton** [comment]
The incorrect README link is relevant to this repository, but the ONC download issue is not and will be discussed in https://github.com/lucascesarfd/onc_dataset/issues/3.

**Comment by Ignasinou** [comment]
Same problem here with the dataset link! Is it supposed to be poiting to DeepShip dataset? Or is there, actually, a "DeeperShip" dataset?

**Comment by lucascesarfd** [comment]
Hi @Ignasinou and @angus-xwu 

Sorry for the late. The README was updated with the correct url. It points to the VTUAD dataset (also updated the dataset class name).

In any case, the link is here:

https://ieee-dataport.org/documents/vtuad-vessel-type-underwater-acoustic-data
