### ISSUE TITLE
Dataset download not working

### ISSUE THREAD

**Issue by ftanago** [lucascesarfd/underwater_snd#5]
Hi Lucas

Thank you for your work on this project. I am trying to get access to the database but the link bring me back to the same web.

Could you share a new link to download the dataset?

Thank you!

**Comment by lucascesarfd** [comment]
Hi @ftanago 

Sorry for the late. The README was updated with the correct url. It points to the VTUAD dataset (also updated the dataset class name).

In any case, the link is here:

https://ieee-dataport.org/documents/vtuad-vessel-type-underwater-acoustic-data
